### ISSUE TITLE
Members not linked after POST operation (BUG)

### ISSUE THREAD

**Issue by AndrewErting** [PICMG/redfish_server_template#12]
A POST request was made to the Accounts resource in the AccountService object (...redfish/v1/AccountService/Accounts), adding a new mock account to the collection. Though this resource is successfully created, it was not automatically linked in the collection's "Members" resource.
Steps to reproduce.
1. Post request to .../AccountService/Accounts
2. Navigate to .../AccountService/Accounts/Members through the browser or make a get request to the URL.
3. See whether or not the newly created account is contained.

**Comment by dsandy12** [comment]
Can you please clarify that this bug no longer exists?  I have been able to add accounts and see them added to the Accounts/Members list.  Here is my process:
1. Obtain credentials by either Redfish session or HTTP Basic methods
2. Using credentials, POST a new ManagerAccount resource to ../AccountService/Accounts
3. Using credentials, GET the representation of the ../AccountService/Accounts resource.  There will be a new member at this point
4. Use the credentials and the new URL in the members collection to GET the new ManagerAccount resource
5. Verify the new resource matches what was POSTed.
