### ISSUE TITLE
XML GitHub Schema Uri's are Invalid (Bug)

### ISSUE THREAD

**Issue by AndrewErting** [PICMG/redfish_server_template#15]
The metadata edmx document returns correct and valid Uri's for all links to the redfish website's schemas but for any links relating to the schemas contained in the IIoT github repository the periods are replaced with slashes. Unclear if this is intentional or not.

1. Steps to reproduce, server maker and server off of WIP_DS branch of server_maker and server_template.
2. Run server and connect
3. View the metadata document and find a Uri linking to a schema on GitHub.

**Comment by dsandy12** [comment]
This was fixed with a commit to the IIoT_mockup project on January 23/2024.
