### ISSUE TITLE
Retrieving password from server (BUG)

### ISSUE THREAD

**Issue by cmunozgo** [PICMG/redfish_server_template#17]
After a POST request is made, if the response is decoded to get a specific field from the accounts resource it can also retrieve the password (encrypted). Based on Redfish Specification this is should not work.

**Comment by dsandy12** [comment]
I have verified that the schema metadata for the password field in the ManagerAccount.v1_11_0 has the property "writeOnly" set to "true".  Based on this, the password should not be returned in the response body.  I have verified this bug and will fix it in the next release.
