### ISSUE TITLE
Atomic Operations missing boolean Attribute "RequireChangePasswordAction"

### ISSUE THREAD

**Issue by cmunozgo** [PICMG/redfish_server_template#18]
Redfish Specification 13.5.1 Account service overview
User accounts **shall** support ETags and atomic operations. Implementations may reject requests
that do not include an ETag. (Ignore Etags)
Redfish Specification 13.5.3 Atomic password changes
If the RequireChangePasswordAction property in the AccountService resource contains true , services
**shall** reject modifications to the Password property in ManagerAccount resources in PATCH or PUT
operations.

**Comment by dsandy12** [comment]
@cmunozgo please only include one "shall" requirement per bug submission.  This allows me to tackle the requirements one at a time.  I have split the ETAG requirement to BUG #30

**Comment by dsandy12** [comment]
fixed with latest commit
