### ISSUE TITLE
PATCH Allows Password to be changed to anything (Finding)

### ISSUE THREAD

**Issue by cmunozgo** [PICMG/redfish_server_template#21]
In the AccountService the Attribute MinPasswordLength is not working correctly for PATCH commands.  Creating an account with a password length lower than MinPasswordLength fails (it should fail), but if a PATCH request is made to the account, the length of the new password is not read and the password in the account resource will be updated to an Illegal password length. (In other words changes the password successfully but it should fail).

**Comment by dsandy12** [comment]
Closed with most recent pull to DEV.
